# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "my-box64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.provider :virtualbox do |vb|
    vb.name = "qPumpkin"
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.network "forwarded_port", guest: 8000, host: 8000
  # config.vm.network "forwarded_port", guest: 8003, host: 8003
  config.vm.network "forwarded_port", guest: 9018, host: 9018
  config.vm.network "forwarded_port", guest: 9019, host: 9019
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.network "forwarded_port", guest: 35729, host: 35729

  config.vm.synced_folder "../design", "/home/vagrant/design"
  config.vm.synced_folder "../src", "/home/vagrant/src"
  config.vm.synced_folder "../hero", "/home/vagrant/hero"
  config.vm.synced_folder "../one", "/home/vagrant/one"
  config.vm.synced_folder "../two", "/home/vagrant/two"
  config.vm.synced_folder "../three", "/home/vagrant/three"
  config.vm.synced_folder "../four", "/home/vagrant/four"

  config.vm.provision "shell", :path => "bootstrap.sh", :privileged => false

end
